# Generated by Django 4.0.5 on 2022-07-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amsakaramentu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nomen', models.CharField(max_length=200)),
                ('domicilium', models.CharField(max_length=200)),
                ('baptizus', models.DateField(null=True)),
                ('com_prima', models.DateField(null=True)),
                ('com_solen', models.DateField(null=True)),
                ('confirmatis', models.DateField(null=True)),
                ('matrimonium', models.DateField(null=True)),
                ('natus', models.DateField(null=True)),
                ('patrinus', models.CharField(max_length=200)),
                ('matrina', models.CharField(max_length=200)),
                ('pater', models.CharField(max_length=200)),
                ('mater', models.CharField(max_length=200)),
                ('status', models.CharField(default='actif', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
