# Generated by Django 4.0.5 on 2022-07-03 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amasakaramentu', '0003_alter_amsakaramentu_baptizus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amsakaramentu',
            name='numero',
        ),
    ]
