# Generated by Django 4.0.5 on 2022-07-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amasakaramentu', '0004_remove_amsakaramentu_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amsakaramentu',
            name='baptizus',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='amsakaramentu',
            name='com_prima',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amsakaramentu',
            name='com_solen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amsakaramentu',
            name='confirmatis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amsakaramentu',
            name='matrimonium',
            field=models.DateField(blank=True, null=True),
        ),
    ]
