# Generated by Django 4.0.5 on 2022-07-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amasakaramentu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amsakaramentu',
            name='baptizus',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='amsakaramentu',
            name='com_prima',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='amsakaramentu',
            name='com_solen',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='amsakaramentu',
            name='confirmatis',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='amsakaramentu',
            name='matrimonium',
            field=models.DateField(default=None, null=True),
        ),
    ]
